### ISSUE TITLE
In safari browser does not support Chinese input

### ISSUE THREAD

**Issue by wallace-yang** [ProseMirror/prosemirror-tables#221]
A number of exception bugs occur, such as exceptions for new columns and input results

**Comment by wallace-yang** [comment]
@ocavue 

https://github.com/ProseMirror/prosemirror-tables/assets/45649432/ed4ff668-da3a-4f91-baad-1eee39b57796

you can check this vide.This problem also appears in the official example.thanks a lot.

**Comment by ocavue** [comment]
@wallace-yang Sorry I cannot reproduce myself. What's your environment (macOS version, Safari version, Chinese input method etc.)?



https://github.com/ProseMirror/prosemirror-tables/assets/24715727/8c4bf234-e20a-4a71-8e28-e938c7e28629

**Comment by wallace-yang** [comment]
> @wallace-yang Sorry I cannot reproduce myself. What's your environment (macOS version, Safari version, Chinese input method etc.)?
> 
>  CleanShot.2024-03-06.at.10.30.04.mp4
Thanks for your reply，All the Safari version have this problem,Google Chrome for mac doesn't have this problem,I guess the problem is caused by the safari browser kernel.
About Chinese input method,I have tried several Chinese input methods, including mac default Chinese input method and third-party input method, and they all have this problem.This question I can confirm is related to the concept of "composition".Therefore, there is a high probability that Japanese, Korean, Arabic and other languages also have this problem.If you don't know how to use the mac's default Chinese input method, you can use this third-party input method, which is the most widely used in China([click me](https://shurufa.sogou.com/) ).
This problem has been bothering me for half a year. Thank you very much for your reply. I have some solutions to share with you, but none of them have been successful because they conflict with the default behavior of prosemiror-tables. If you can help me with these conflicts, that would be also great.
I tried to add a non-removable "<span>&ZeroWidthSpace;</span> "to each "td" or "th" by the "decorations ";  solves this problem, but raises another issue.Here is the code。
```javascript 
              allCellsArr.forEach(({ pos }, index) => {
                decorations.push(
                  Decoration.widget(pos + 1, () => {
                    const grip = document.createElement("span");
                    grip.style = "display: block;line-height:0px;";
                    grip.innerHTML = "&ZeroWidthSpace;";
                    return grip;
                  })
                );
              });
```
But it raises new questions like this：

https://github.com/ProseMirror/prosemirror-tables/assets/45649432/55adf070-5a8c-4806-8860-e48cfea95d32


Feishu, the largest rich text editor product in China, uses this solution, and they disable the entry of any characters after selecting a table cell, so this problem does not arise.I would also like to disable input after cell selection, but disabling is not 100% effective.This is my code.
```javascript 
new Plugin({
        props: {
          handleDOMEvents: {
            keydown (view, event) {
              console.log("🚀 ~ keydown ~ event:", event);
              if (hadSelectedCell(view) && ((event.keyCode >= 65 && event.keyCode <= 90) || event.keyCode === 229)) {
                console.log("🚀 ~ keydown ~ hadSelectedCell,disable!!!!!!", event);
                event.preventDefault();
                return true;
              }
            }
          }
       }
})
```
The Chinese input method is sometimes disabled and sometimes invalid, but it is effective in the English state.The result like this:

https://github.com/ProseMirror/prosemirror-tables/assets/45649432/a71e68af-ad40-4a31-851f-616c7d3af27a


If you want my device info, the following two pictures are my device information.
<img width="280" alt="截屏2024-03-06 09 52 47" src="https://github.com/ProseMirror/prosemirror-tables/assets/45649432/5b438525-189f-4de0-9b72-66dcf427619e">
![截屏2024-03-06 09 53 58](https://github.com/ProseMirror/prosemirror-tables/assets/45649432/69de4770-75d5-46ad-b4eb-21971cb9dadc)

Expect your reply, thank you.

**Comment by ocavue** [comment]
https://github.com/ProseMirror/prosemirror-tables/assets/24715727/f6d9d24e-3296-4a42-a2ba-0ae331fd9f49

I can reproduce this bug. This bug only occurs inside an empty table cell.

---

After some debugging, I found that Safari produces different `mutations` in [this line](https://github.com/prosemirror/prosemirror-view/blob/5f7203cfc3dbc4231fe4214f3b4d5e572516d57b/src/domobserver.ts#L168) compared to Chrome and Firefox. When you type something with Chinese IME in an empty cell, Safari will first try to delete the whole `<p>` element with all the Pinyin letters, then add a new `<p>` element  including the Chinese characters. However, the first `<p>` removal is invalid because prosemirror-tables [requires](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/demo/demo.ts#L37) every cell to have at least one block. 

It seems that there is already some code in the prosemirror-view package that patches the table behavior in Safari ([code link](https://github.com/prosemirror/prosemirror-view/blob/e5e9e15e1d00cea55914f520877c12add996b742/src/domchange.ts#L70)). Maybe it's possible to add some more code in the prosemirror-view to workaround this. However, I don't understand how to do that sadlly. 

I did find another workaround during debugging. It seems that once I remove the [`position: relative;`](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/style/tables.css#L14) CSS rules, this issue doesn't occur anymore. Removing `position: relative;` will break the column-resize-handle so I cannot simply add this patch to prosemirror-tables.

**Comment by wallace-yang** [comment]
> CleanShot.2024-03-16.at.22.03.20.mp4 
> I can reproduce this bug. This bug only occurs inside an empty table cell.
> 
> After some debugging, I found that Safari produces different `mutations` in [this line](https://github.com/prosemirror/prosemirror-view/blob/5f7203cfc3dbc4231fe4214f3b4d5e572516d57b/src/domobserver.ts#L168) compared to Chrome and Firefox. When you type something with Chinese IME in an empty cell, Safari will first try to delete the whole `<p>` element with all the Pinyin letters, then add a new `<p>` element including the Chinese characters. However, the first `<p>` removal is invalid because prosemirror-tables [requires](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/demo/demo.ts#L37) every cell to have at least one block.
> 
> It seems that there is already some code in the prosemirror-view package that patches the table behavior in Safari ([code link](https://github.com/prosemirror/prosemirror-view/blob/e5e9e15e1d00cea55914f520877c12add996b742/src/domchange.ts#L70)). Maybe it's possible to add some more code in the prosemirror-view to workaround this. However, I don't understand how to do that sadlly.
> 
> I did find another workaround during debugging. It seems that once I remove the [`position: relative;`](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/style/tables.css#L14) CSS rules, this issue doesn't occur anymore. Removing `position: relative;` will break the column-resize-handle so I cannot simply add this patch to prosemirror-tables.

@ocavue Thank you very much for your valuable information. If I have other solutions in the future, I will reply here.

**Comment by dragonman225** [comment]
I wonder if these are related:
- https://discuss.prosemirror.net/t/ime-composing-problems-on-td-or-th-element-in-safari-browser/4501
- https://github.com/Milkdown/milkdown/blob/main/packages/preset-gfm/src/plugin/auto-insert-zero-space-plugin.ts

**Comment by zunsthy** [comment]
I'm also troubled by this problem, 

> CleanShot.2024-03-16.at.22.03.20.mp4
> 
> I can reproduce this bug. This bug only occurs inside an empty table cell.
> 
> After some debugging, I found that Safari produces different `mutations` in [this line](https://github.com/prosemirror/prosemirror-view/blob/5f7203cfc3dbc4231fe4214f3b4d5e572516d57b/src/domobserver.ts#L168) compared to Chrome and Firefox. When you type something with Chinese IME in an empty cell, Safari will first try to delete the whole `<p>` element with all the Pinyin letters, then add a new `<p>` element including the Chinese characters. However, the first `<p>` removal is invalid because prosemirror-tables [requires](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/demo/demo.ts#L37) every cell to have at least one block.
> 
> It seems that there is already some code in the prosemirror-view package that patches the table behavior in Safari ([code link](https://github.com/prosemirror/prosemirror-view/blob/e5e9e15e1d00cea55914f520877c12add996b742/src/domchange.ts#L70)). Maybe it's possible to add some more code in the prosemirror-view to workaround this. However, I don't understand how to do that sadlly.
> 
> I did find another workaround during debugging. It seems that once I remove the [`position: relative;`](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/style/tables.css#L14) CSS rules, this issue doesn't occur anymore. Removing `position: relative;` will break the column-resize-handle so I cannot simply add this patch to prosemirror-tables.

Resizing cell and IME inputing will not happen at the same time. If toggling position property value on `compositionstart` and `compositionend` events, can it work?

**Comment by wallace-yang** [comment]
@ocavue Hi! I have resolve this issue😊
[Support for Chinese, Japanese, and Korean IME in Safari browser. #232](https://github.com/ProseMirror/prosemirror-tables/pull/232)

**Comment by ocavue** [comment]
It seems that this Safari bug not only affect prosemirror-tables, so I created a standalone package [prosemirror-safari-ime-span](https://github.com/ocavue/prosemirror-safari-ime-span) to address this issue. Could you try https://ocavue-fix-safari--prosemirror-tables.netlify.app/ and see if everything works fine?

**Comment by wallace-yang** [comment]
> It seems that this Safari bug not only affect prosemirror-tables, so I created a standalone package [prosemirror-safari-ime-span](https://github.com/ocavue/prosemirror-safari-ime-span) to address this issue. Could you try https://ocavue-fix-safari--prosemirror-tables.netlify.app/ and see if everything works fine?

When I select a cell, move the mouse to an empty cell, and then input Chinese characters, a bug will occur.Some letters that should have been displayed are missing.

https://github.com/ProseMirror/prosemirror-tables/assets/45649432/1ece275d-e405-4a10-ad53-3e205aa1fc88

**Comment by ocavue** [comment]
Sorry for the late reply.

> When I select a cell, move the mouse to an empty cell, and then input Chinese characters, a bug will occur.Some letters that should have been displayed are missing.

I'm unable to reproduce this with my Safari Version 17.5 (19618.2.12.11.6). What's your Safari version. 

Although I cannot reproduce, I pushed a patch that reduces the state update when the IME is enabled or disabled. Could you try https://ocavue-fix-safari--prosemirror-tables.netlify.app/  again and see if this issue still occurs?

**Comment by wallace-yang** [comment]
> this issue still occurs

This issue still occurs，However, bugs occur randomly, not necessarily every time, with a probability of about 30%.

https://github.com/user-attachments/assets/6b2f98fa-e24d-469f-9ccb-6fdb07fa8bb8

my Safari Version 17.4 (19618.1.15.11.12)

**Comment by ocavue** [comment]
Could you check if you can reproduce this bug using [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) v18.0+? I cannot reproduce after many tries using Safari Version 17.5 and Safari Technology Preview 18.0.

**Comment by wallace-yang** [comment]
> Could you check if you can reproduce this bug using [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) v18.0+?
> 
> I cannot reproduce after many tries using Safari Version 17.5 and Safari Technology Preview 18.0, so I suspect that it's a bug in 17.4 that has been fixed.

I have already downloaded and used Safari Technology Preview, but the issue still persists. Additionally, the problem occurs even when the target cell is not empty. Here are my Safari Technology Preview and device information.

https://github.com/user-attachments/assets/7aa2fee9-75aa-4cdc-8167-e295214fd5ce
<img width="287" alt="image" src="https://github.com/user-attachments/assets/8a4f59a4-2157-46dc-a472-5cf5cf1cdec5">

<img width="312" alt="截屏2024-07-23 11 12 49" src="https://github.com/user-attachments/assets/e5264b1a-3999-4834-8fdb-6729c43657f3">

**Comment by wallace-yang** [comment]
> Could you check if you can reproduce this bug using [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) v18.0+?
> 
> I cannot reproduce after many tries using Safari Version 17.5 and Safari Technology Preview 18.0, so I suspect that it's a bug in 17.4 that has been fixed.

I have already downloaded and used Safari Technology Preview, but the issue still persists. Additionally, the problem occurs even when the target cell is not empty. Here are my Safari Technology Preview and device information.

<img width="287" alt="image" src="https://github.com/user-attachments/assets/8a4f59a4-2157-46dc-a472-5cf5cf1cdec5">

<img width="312" alt="截屏2024-07-23 11 12 49" src="https://github.com/user-attachments/assets/e5264b1a-3999-4834-8fdb-6729c43657f3">

https://github.com/user-attachments/assets/bad2a02d-150d-47cb-8398-e42d5ddfc70a

**Comment by zizdlp** [comment]
> I can reproduce this bug. This bug only occurs inside an empty table cell.
> 
> After some debugging, I found that Safari produces different `mutations` in [this line](https://github.com/prosemirror/prosemirror-view/blob/5f7203cfc3dbc4231fe4214f3b4d5e572516d57b/src/domobserver.ts#L168) compared to Chrome and Firefox. When you type something with Chinese IME in an empty cell, Safari will first try to delete the whole `<p>` element with all the Pinyin letters, then add a new `<p>` element including the Chinese characters. However, the first `<p>` removal is invalid because prosemirror-tables [requires](https://github.com/ProseMirror/prosemirror-tables/blob/67371611fa9964c20d7d8be741f88ea8b3c24900/demo/demo.ts#L37) every cell to have at least one block.
> 
While using remirror, I also encountered a type issue, which I temporarily resolved with a small trick: adding a plugin that inserts an invisible placeholder in each cell; this ensures that no cell is left empty.

If anyone is still stuck with this issue, I hope this trick will work.

<img width="671" alt="Image" src="https://github.com/user-attachments/assets/46f610ff-8198-4cce-92e3-918d99e103c5" />

**Comment by ghost** [comment]
I've been looking into this and drafted a potential fix in PR https://github.com/ProseMirror/prosemirror-view/pull/188. It seems to work well in my local testing for the Safari IME bug. Could you guys verify if this solves the problem on your end?

**Comment by patgu9** [comment]
I am also experiencing this exact same issue on the latest demo site (https://prosemirror-tables.netlify.app). 

My environment is:

<img width="284" height="206" alt="Image" src="https://github.com/user-attachments/assets/f87471a3-acf3-4fc2-a122-53bb2bf72b39" />

**Comment by patgu9** [comment]
Just a heads up for everyone following this issue:

The upstream fix for this Safari table IME bug was recently merged and released in prosemirror-view@1.41.5 (https://github.com/ProseMirror/prosemirror-view/commit/1773eacd5544b1669c75d352b1ec42d56b315c74). If you bump your prosemirror-view dependency to >= 1.41.5, it successfully prevents the composition text from jumping out of the empty table cell! 🎉
