### ISSUE TITLE
Can't place cursor before or after table

### ISSUE THREAD

**Issue by mjmasn** [ProseMirror/prosemirror-tables#5]
If there is no existing content before or after a table at the time it is inserted, it is impossible to place the cursor before or after the table. A cursor line appears for a brief few milliseconds before the selection is placed inside the first or last table cell.

Dragging and holding such that the large cursor line starts flickering sometimes allows you to insert text before or after the table if you time it just right.

![tables](https://user-images.githubusercontent.com/2977095/30383103-c9c1b82e-9898-11e7-8e92-154b5d950208.gif)

There also appears to be an issue (also shown in the gif), where pressing `Enter` inside a cell sometimes inserts new rows or columns, somewhat randomly from what I can see. Let me know if I should open a new issue for that.

I'm happy to have a go at solving this one if you can provide any pointers as to where and why this might be happening.

**Comment by eshvedai** [comment]
This is expected as table is a block element. You might be interested in this package: https://github.com/ProseMirror/prosemirror-gapcursor

With regards to pressing `Enter` bug, please open a new issue.

**Comment by mjmasn** [comment]
Sorry I should have said, this is with the gapcursor installed (and it does work for horizontal rules). 

After a bit more investigation, it seems the gapcursor can be made to appear by clicking whitespace inside a cell but not before or after the table, (specifically the bottom right cell if you want to add content after the table rather than splitting it), then pressing shift-enter.

For quotes, gapcursor doesn't appear but pressing enter then clicking lift out of enclosing block does give a new paragraph. 

This is using the collab example, plus the tables plugin.

**Comment by marijnh** [comment]
This should be fixed in prosemirror-gapcursor 0.23.1

**Comment by eshvedai** [comment]
updated `prosemirror-tables` to `0.2.0` that uses `0.23` of ProseMirror.

**Comment by Winston-Guess** [comment]
I'm still having issues with clicking before or after a table when the table is the only element on the page. I can use the up arrow on the first cell or down arrow on the last cell to place the gap cursor before and after the table, respectively. However, I cannot click to get to these locations unless there is text content above/below the table. Is this just a ProseMirror limitation or am I missing something?
